name: 'initialize docker container environment '
description: 'prepare the container to run the target script(s)'
inputs:
  github-pat:
    description: >
      Personal access token (PAT) used by actions/checkout@v2 
      to fetch the repository. Note that github token
      can be used only for the working directory. 
runs:
  using: "composite"
  steps:
    - name: github issue workaround
      run: |
        #BUG: https://github.com/actions/runner/issues/863
        #On Github Actions, container default user is root
        #However, the $HOME folder is changed to /github/home
        #TODO: elixir dependencies migration
        rm -f $HOME/.ssh/config
        cp -a /root/. $HOME/
      shell: bash
