name: 'initialize docker container environment '

description: 'prepare the container to run the target script(s)'

runs:
  using: "composite"
  steps:
    - name: github issue workaround
      run: |
        #BUG: https://github.com/actions/runner/issues/863
        #On Github Actions, container default user is root
        #However, the $HOME folder is changed to /github/home
        #TODO: elixir dependencies migration
        echo $(whoami)
        source /etc/os-release
        echo "${ID}"
        case "${ID}" in
            debian|ubuntu)
                apt-get update -y
                apt-get install -y sudo jq
                ;;
            amzn)
                yum update -y
                yum install -y sudo tar jq
                ;;
            *)
                echo "Unsupported OS: ${ID}. Please check with DevSecOps."
                exit 1
                ;;
        esac

        sudo rm -f $HOME/.ssh/config
        sudo cp -a /root/. $HOME/
      shell: bash
